-- =============================================
-- Conversation Archive Schema
-- Run this in Supabase SQL Editor
-- =============================================

-- Table for archiving expired conversations (for future training)
CREATE TABLE IF NOT EXISTS conversation_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR NOT NULL,              -- User identifier (PSID for Messenger)
    conversation_data JSONB NOT NULL,       -- Array of message objects
    started_at TIMESTAMPTZ,                 -- When conversation started
    ended_at TIMESTAMPTZ,                   -- When conversation ended (30min timeout)
    message_count INT,                      -- Number of messages in conversation
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster queries by user
CREATE INDEX IF NOT EXISTS idx_conversation_archive_user_id ON conversation_archive(user_id);

-- Index for date-based queries
CREATE INDEX IF NOT EXISTS idx_conversation_archive_created_at ON conversation_archive(created_at);
