-- =============================================
-- Messenger Integration Schema
-- Run this in Supabase SQL Editor
-- =============================================

-- Table for Messenger-specific logs
CREATE TABLE IF NOT EXISTS messenger_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psid VARCHAR NOT NULL,              -- Facebook Page-Scoped User ID
    message_type VARCHAR(20),           -- 'incoming' or 'outgoing'
    message_text TEXT,                  -- Original user message
    response_text TEXT,                 -- Bot response
    latency_ms INT,                     -- Response time in milliseconds
    event_type VARCHAR(50) DEFAULT 'message',  -- message, postback, etc.
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster queries by user
CREATE INDEX IF NOT EXISTS idx_messenger_logs_psid ON messenger_logs(psid);

-- Index for date-based queries
CREATE INDEX IF NOT EXISTS idx_messenger_logs_created_at ON messenger_logs(created_at);

-- =============================================
-- Optional: View for Messenger Statistics
-- =============================================

CREATE OR REPLACE VIEW messenger_daily_stats AS
SELECT 
    DATE(created_at) as date,
    COUNT(*) FILTER (WHERE message_type = 'incoming') as incoming_count,
    COUNT(*) FILTER (WHERE message_type = 'outgoing') as outgoing_count,
    COUNT(DISTINCT psid) as unique_users,
    ROUND(AVG(latency_ms) FILTER (WHERE latency_ms IS NOT NULL), 2) as avg_latency_ms
FROM messenger_logs
GROUP BY DATE(created_at)
ORDER BY date DESC;
